version: "3.4"

services:
  backend:
    image: ${IMAGE_NAME}
    restart: always
    build:
      context: .
      dockerfile: ./dockerfile
    environment:
      # Manually set environments
      DB: ${DB}
      DB_IP: ${DB_IP}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      TEST_USERNAME: ${TEST_USERNAME}
      TEST_PASSWORD: ${TEST_PASSWORD}
      # Manually change ports
    ports:
      - 80:3000
