Write-Host "`ndeploy.ps1 v1.2.3`n`n" -ForegroundColor "Green"
Set-Location "../jmas-padron-frontend"
powershell "git checkout main"
Write-Host "`nBuilding frontend project...`n" -ForegroundColor "Green"
powershell "npm run build:test"
Write-Host "`nCopying contents of dist`n" -ForegroundColor "Green"
Copy-Item -Path '.\\dist\\*' -Destination "..\\jmas-padron-backend\\public\\" -Recurse -Force
Set-Location "../jmas-padron-backend"
powershell "git checkout main"
Write-Host "`nCommiting and pushing changes`n" -ForegroundColor "Green"
powershell "git add ."
powershell "git commit -a -m 'chore(frontend): update frontend dist files'"
powershell "git push git@gitlab.com:webmasteremobile/jmas-cuauhtemoc-backend.git main"
Write-Host "`nTo build and deploy connect to prod server..." -ForegroundColor "Green"
Write-Host "`nDone!`n" -ForegroundColor "Green"
